"""
FIRS E-Invoice API client (NRS E-Invoice Collection v1).

Auth:    x-api-key + x-api-secret headers on every request (no token fetch needed).
Flow:    POST /api/v1/invoice/validate  →  POST /api/v1/invoice/sign  →  (optional) POST /api/v1/invoice/transmit/{irn}
IRN:     Generated by the seller: {BUSINESS_CODE}-{MD5_HASH}-{YYYYMMDD}
Format:  JSON (UBL BIS Billing 3.0 field names) — XML variants exist but we use JSON throughout.

All settings are read from Nigeria Compliance Settings (single DocType).
Ref:     https://documenter.getpostman.com/view/38144164/2sAXqtagFx
"""
from __future__ import annotations

import hashlib
import json
from typing import Any

import frappe
import requests
from frappe import _
from frappe.utils import now_datetime, add_to_date, nowdate

_SETTINGS_DOCTYPE = "Nigeria Compliance Settings"
_MAX_RETRIES = 3
_TIMEOUT_SHORT = 30
_TIMEOUT_LONG = 60


class EInvoiceError(Exception):
    pass


class EInvoiceValidationError(EInvoiceError):
    """400/422 from FIRS — permanent failure, do not retry."""
    pass


# ── Settings helpers ──────────────────────────────────────────────────────────

def _get_settings():
    return frappe.get_cached_doc(_SETTINGS_DOCTYPE)


def _base_url(settings) -> str:
    if settings.einvoice_environment == "Production":
        return (settings.einvoice_production_url or "https://api.einvoice.firs.gov.ng").rstrip("/")
    return (settings.einvoice_sandbox_url or "https://api-sandbox.einvoice.firs.gov.ng").rstrip("/")


def _headers(settings) -> dict:
    """
    Auth is permanent API key + secret headers — no token fetch, no Bearer token.
    Every request carries x-api-key and x-api-secret.
    """
    return {
        "x-api-key": settings.get_password("einvoice_api_key"),
        "x-api-secret": settings.get_password("einvoice_api_secret"),
        "Content-Type": "application/json",
    }


# ── IRN generation ─────────────────────────────────────────────────────────────

def generate_irn(business_code: str, invoice_name: str) -> str:
    """
    Generate a FIRS-format IRN: {BUSINESS_CODE}-{MD5_HASH_8}-{YYYYMMDD}

    The IRN is created by the seller (us) before submission.
    FIRS validates the format and uniqueness on /invoice/irn/validate.

    Example: ITW20853450-6997D6BB-20240703
    """
    today = now_datetime().strftime("%Y%m%d")
    hash_part = hashlib.md5(
        f"{business_code}:{invoice_name}:{today}".encode()
    ).hexdigest()[:8].upper()
    return f"{business_code}-{hash_part}-{today}"


# ── Payload builder ────────────────────────────────────────────────────────────

def build_invoice_payload(sales_invoice: str, irn: str) -> dict[str, Any]:
    """
    Build UBL BIS Billing 3.0 JSON payload for POST /api/v1/invoice/validate
    and POST /api/v1/invoice/sign (same body for both).

    Field names follow the actual FIRS API spec (UBL standard snake_case).
    Ref: https://documenter.getpostman.com/view/38144164/2sAXqtagFx#ValidateInvoice
    """
    doc = frappe.get_doc("Sales Invoice", sales_invoice)
    settings = _get_settings()

    from zinye_ng.nigeria.constants.invoice_types import get_invoice_type_code
    from zinye_ng.nigeria.constants.payment_means import get_payment_means_code
    from zinye_ng.nigeria.constants.tax_categories import get_tax_category_code
    from zinye_ng.nigeria.firs.resources import get_quantity_code

    # ── Business IDs ────────────────────────────────────────────────────────
    business_id = (
        frappe.db.get_value("Company", doc.company, "ng_firs_business_id")
        or settings.get("einvoice_business_id")
        or ""
    )
    seller_tin = (
        frappe.db.get_value("Company", doc.company, "ng_tin")
        or settings.tin
        or ""
    )
    buyer_tin = frappe.db.get_value("Customer", doc.customer, "ng_tin") or ""

    # ── Invoice type ─────────────────────────────────────────────────────────
    is_return = bool(doc.get("is_return"))
    is_debit_note = bool(doc.get("is_debit_note"))
    invoice_type_code = get_invoice_type_code("Sales Invoice", is_return, is_debit_note)

    # ── Addresses ─────────────────────────────────────────────────────────────
    company_doc = frappe.get_doc("Company", doc.company)
    seller_address = _build_postal_address(
        frappe.db.get_value("Company", doc.company, "ng_address") or "",
        frappe.db.get_value("Company", doc.company, "ng_city") or "",
        frappe.db.get_value("Company", doc.company, "ng_postal_code") or "",
        "NG",
    )
    buyer_address = _build_postal_address(
        doc.get("customer_address") or "",
        "",
        "",
        "NG",
    )

    # ── Tax ───────────────────────────────────────────────────────────────────
    vat_rate = float(settings.einvoice_default_vat_rate or 7.5)
    tax_category_code = get_tax_category_code(vat_rate)

    # ── Payment means ─────────────────────────────────────────────────────────
    payment_mode = doc.get("ng_payment_means") or doc.get("mode_of_payment") or ""
    payment_means_code = get_payment_means_code(payment_mode)
    due_date = str(doc.due_date) if doc.get("due_date") else str(doc.posting_date)

    # ── Line items ────────────────────────────────────────────────────────────
    invoice_lines = []
    total_vat = 0.0
    total_line_extension = 0.0

    for row in doc.items:
        net = float(row.net_amount)
        line_vat = round(net * (vat_rate / 100), 2)
        total_vat += line_vat
        total_line_extension += net

        item_fields = frappe.db.get_value(
            "Item", row.item_code,
            ["ng_hs_code", "ng_service_code", "ng_product_category"],
            as_dict=True,
        ) or {}
        hs_code = item_fields.get("ng_hs_code") or item_fields.get("ng_service_code") or ""
        product_category = item_fields.get("ng_product_category") or ""
        quantity_code = get_quantity_code(row.uom or "")

        invoice_lines.append({
            "hsn_code": hs_code or row.item_code,
            "product_category": product_category or row.item_group or "",
            "invoiced_quantity": float(row.qty),
            "line_extension_amount": net,
            "item": {
                "name": row.item_name or row.item_code,
                "description": row.description or row.item_name or "",
                "sellers_item_identification": row.item_code,
            },
            "price": {
                "price_amount": float(row.rate),
                "base_quantity": 1,
                "price_unit": f"{doc.currency or 'NGN'} per {quantity_code}",
            },
        })

    total_vat = round(total_vat, 2)
    tax_exclusive = round(float(doc.net_total), 2)
    tax_inclusive = round(float(doc.grand_total), 2)
    payable_amount = round(float(doc.outstanding_amount or doc.grand_total), 2)

    return {
        # ── Invoice header ──────────────────────────────────────────────────
        "business_id": business_id,
        "irn": irn,
        "issue_date": str(doc.posting_date),
        "due_date": due_date,
        "issue_time": now_datetime().strftime("%H:%M:%S"),
        "invoice_type_code": invoice_type_code,
        "payment_status": "PENDING",
        "document_currency_code": doc.currency or "NGN",
        "tax_currency_code": "NGN",

        # ── Supplier ────────────────────────────────────────────────────────
        "accounting_supplier_party": {
            "party_name": doc.company,
            "tin": seller_tin,
            "email": frappe.db.get_value("Company", doc.company, "email") or "",
            "telephone": frappe.db.get_value("Company", doc.company, "phone_no") or "",
            "business_description": company_doc.company_description or "",
            "postal_address": seller_address,
        },

        # ── Customer ─────────────────────────────────────────────────────────
        "accounting_customer_party": {
            "party_name": doc.customer_name,
            "tin": buyer_tin,
            "email": frappe.db.get_value("Customer", doc.customer, "email_id") or "",
            "telephone": frappe.db.get_value("Customer", doc.customer, "mobile_no") or "",
            "postal_address": buyer_address,
        },

        # ── Payment ──────────────────────────────────────────────────────────
        "payment_means": [
            {
                "payment_means_code": payment_means_code,
                "payment_due_date": due_date,
            }
        ],
        "payment_terms_note": doc.payment_terms_template or "",

        # ── Tax ──────────────────────────────────────────────────────────────
        "tax_total": [
            {
                "tax_amount": total_vat,
                "tax_subtotal": [
                    {
                        "taxable_amount": tax_exclusive,
                        "tax_amount": total_vat,
                        "tax_category": {
                            "id": tax_category_code,
                            "percent": vat_rate,
                        },
                    }
                ],
            }
        ],

        # ── Totals ────────────────────────────────────────────────────────────
        "legal_monetary_total": {
            "line_extension_amount": round(total_line_extension, 2),
            "tax_exclusive_amount": tax_exclusive,
            "tax_inclusive_amount": tax_inclusive,
            "payable_amount": payable_amount,
        },

        # ── Lines ─────────────────────────────────────────────────────────────
        "invoice_line": invoice_lines,
    }


def _build_postal_address(street: str, city: str, postal_zone: str, country: str) -> dict:
    return {
        "street_name": street or "",
        "city_name": city or "",
        "postal_zone": postal_zone or "",
        "country": country or "NG",
    }


# ── IRN pre-validation ────────────────────────────────────────────────────────

def validate_irn(irn: str, invoice_reference: str, business_id: str) -> dict[str, Any]:
    """
    POST /api/v1/invoice/irn/validate
    Validates that the generated IRN is unique and correctly formatted before submission.
    """
    settings = _get_settings()
    resp = requests.post(
        f"{_base_url(settings)}/api/v1/invoice/irn/validate",
        json={
            "invoice_reference": invoice_reference,
            "business_id": business_id,
            "irn": irn,
        },
        headers=_headers(settings),
        timeout=_TIMEOUT_SHORT,
    )
    if not resp.ok:
        raise EInvoiceError(f"IRN validation failed [{resp.status_code}]: {resp.text}")
    return resp.json() if resp.content else {}


# ── Submission ────────────────────────────────────────────────────────────────

def submit_invoice_enqueued(sales_invoice: str) -> dict:
    """
    Enqueue FIRS submission as a background job.
    Use from on_submit hooks and manual form buttons.
    """
    settings = _get_settings()
    if not settings.einvoice_enabled:
        return {}

    frappe.enqueue(
        "zinye_ng.nigeria.firs.einvoice.submit_invoice",
        queue="default",
        timeout=180,
        enqueue_after_commit=True,
        sales_invoice=sales_invoice,
    )
    return {"queued": True}


def submit_invoice(sales_invoice: str) -> dict[str, Any]:
    """
    Full 3-step FIRS submission (runs in background queue):
      1. Generate IRN
      2. POST /api/v1/invoice/validate — check payload for errors
      3. POST /api/v1/invoice/sign    — sign and finalise

    Creates or updates a Nigeria E-Invoice record with the result.
    """
    settings = _get_settings()
    if not settings.einvoice_enabled:
        return {}

    einvoice_doc = _get_or_create_einvoice(sales_invoice)
    if einvoice_doc.status == "Cleared":
        return {}

    if (einvoice_doc.retry_count or 0) >= (einvoice_doc.max_retries or _MAX_RETRIES):
        frappe.log_error(
            f"Max retries reached for Sales Invoice {sales_invoice}",
            "FIRS e-Invoice",
        )
        return {}

    # Respect B2B-only setting
    actual_buyer_tin = frappe.db.get_value(
        "Customer",
        frappe.db.get_value("Sales Invoice", sales_invoice, "customer"),
        "ng_tin",
    ) or ""
    if settings.einvoice_b2b_only and not actual_buyer_tin:
        return {}

    business_id = (
        frappe.db.get_value(
            "Company",
            frappe.db.get_value("Sales Invoice", sales_invoice, "company"),
            "ng_firs_business_id",
        )
        or settings.get("einvoice_business_id")
        or ""
    )

    try:
        # Use existing IRN if already generated (retry scenario)
        irn = einvoice_doc.irn or generate_irn(business_id or "NG", sales_invoice)

        payload = build_invoice_payload(sales_invoice, irn)

        # Step 1: Validate
        validate_resp = requests.post(
            f"{_base_url(settings)}/api/v1/invoice/validate",
            json=payload,
            headers=_headers(settings),
            timeout=_TIMEOUT_LONG,
        )

        if validate_resp.status_code in (400, 422):
            _update_einvoice(einvoice_doc, payload, {}, "Failed",
                             f"Validation error: {validate_resp.text}", irn=irn)
            raise EInvoiceValidationError(
                f"FIRS validation error [{validate_resp.status_code}]: {validate_resp.text}"
            )

        if not validate_resp.ok:
            _update_einvoice(einvoice_doc, payload, {}, "Auto-Retry",
                             f"Validate step error: {validate_resp.text}", irn=irn)
            _flag_retry_pending()
            return {}

        # Step 2: Sign
        sign_resp = requests.post(
            f"{_base_url(settings)}/api/v1/invoice/sign",
            json=payload,
            headers=_headers(settings),
            timeout=_TIMEOUT_LONG,
        )

        if sign_resp.status_code in (400, 422):
            _update_einvoice(einvoice_doc, payload, {}, "Failed",
                             f"Sign error: {sign_resp.text}", irn=irn)
            raise EInvoiceValidationError(
                f"FIRS sign error [{sign_resp.status_code}]: {sign_resp.text}"
            )

        if not sign_resp.ok:
            _update_einvoice(einvoice_doc, payload, {}, "Auto-Retry",
                             f"Sign step error: {sign_resp.text}", irn=irn)
            _flag_retry_pending()
            return {}

        result = sign_resp.json() if sign_resp.content else {}
        csid = result.get("csid") or result.get("CSID") or ""
        qr_data = result.get("qrCode") or result.get("QRCode") or result.get("qr_code") or ""

        _update_einvoice(einvoice_doc, payload, result, "Submitted", "", irn=irn, csid=csid, qr_data=qr_data)

        frappe.db.set_value("Sales Invoice", sales_invoice, {
            "ng_firs_irn": irn,
            "ng_firs_csid": csid,
            "ng_firs_status": "Submitted",
        })
        return result

    except (EInvoiceValidationError, EInvoiceError):
        raise
    except Exception as e:
        _update_einvoice(einvoice_doc, {}, {}, "Auto-Retry", str(e))
        _flag_retry_pending()
        frappe.log_error(frappe.get_traceback(), "FIRS e-Invoice Submission")
        return {}


def _flag_retry_pending():
    frappe.db.set_value(_SETTINGS_DOCTYPE, _SETTINGS_DOCTYPE, "is_retry_einvoice_pending", 1)
    frappe.db.commit()


# ── Transmit ──────────────────────────────────────────────────────────────────

def transmit_invoice(irn: str) -> dict[str, Any]:
    """
    POST /api/v1/invoice/transmit/{irn}
    Sends a signed invoice to the buyer via FIRS network.
    Called after successful sign, or manually from the form.
    """
    settings = _get_settings()
    resp = requests.post(
        f"{_base_url(settings)}/api/v1/invoice/transmit/{irn}",
        headers=_headers(settings),
        timeout=_TIMEOUT_SHORT,
    )
    if not resp.ok:
        raise EInvoiceError(f"FIRS transmit failed [{resp.status_code}]: {resp.text}")
    return resp.json() if resp.content else {}


def lookup_transmit_status(irn: str) -> dict[str, Any]:
    """GET /api/v1/invoice/transmit/lookup/{irn} — check transmit status."""
    settings = _get_settings()
    resp = requests.get(
        f"{_base_url(settings)}/api/v1/invoice/transmit/lookup/{irn}",
        headers=_headers(settings),
        timeout=_TIMEOUT_SHORT,
    )
    if not resp.ok:
        raise EInvoiceError(f"FIRS transmit lookup failed [{resp.status_code}]: {resp.text}")
    return resp.json() if resp.content else {}


# ── Post-submission operations ─────────────────────────────────────────────────

def confirm_invoice(irn: str) -> dict[str, Any]:
    """
    GET /api/v1/invoice/confirm/{irn}
    Confirms an invoice. Updates local status to Cleared.
    """
    settings = _get_settings()
    resp = requests.get(
        f"{_base_url(settings)}/api/v1/invoice/confirm/{irn}",
        headers=_headers(settings),
        timeout=_TIMEOUT_SHORT,
    )
    if not resp.ok:
        raise EInvoiceError(f"FIRS confirm failed [{resp.status_code}]: {resp.text}")

    result = resp.json() if resp.content else {}

    # Update local e-invoice status to Cleared
    name = frappe.db.get_value("Nigeria E-Invoice", {"irn": irn}, "name")
    if name:
        frappe.db.set_value("Nigeria E-Invoice", name, {
            "status": "Cleared",
            "cleared_at": now_datetime(),
        })
        doc = frappe.get_doc("Nigeria E-Invoice", name)
        frappe.db.set_value("Sales Invoice", doc.sales_invoice, "ng_firs_status", "Cleared")
        frappe.db.commit()
    return result


def update_payment_status(irn: str, payment_status: str, reference: str = "") -> dict[str, Any]:
    """
    PATCH /api/v1/invoice/update/{irn}
    Updates payment status: PENDING | PAID | REJECTED.
    Call when a Sales Invoice is paid/reconciled.
    """
    if payment_status not in ("PENDING", "PAID", "REJECTED"):
        raise EInvoiceError(f"Invalid payment_status: {payment_status}. Must be PENDING, PAID, or REJECTED.")

    settings = _get_settings()
    body: dict = {"payment_status": payment_status}
    if reference:
        body["reference"] = reference

    resp = requests.patch(
        f"{_base_url(settings)}/api/v1/invoice/update/{irn}",
        json=body,
        headers=_headers(settings),
        timeout=_TIMEOUT_SHORT,
    )
    if not resp.ok:
        raise EInvoiceError(f"FIRS update failed [{resp.status_code}]: {resp.text}")
    return resp.json() if resp.content else {}


def download_invoice(irn: str) -> bytes:
    """
    GET /api/v1/invoice/download/{irn}
    Returns raw invoice bytes (XML or PDF depending on Accept header).
    """
    settings = _get_settings()
    headers = dict(_headers(settings))
    resp = requests.get(
        f"{_base_url(settings)}/api/v1/invoice/download/{irn}",
        headers=headers,
        timeout=_TIMEOUT_LONG,
    )
    if not resp.ok:
        raise EInvoiceError(f"FIRS download failed [{resp.status_code}]: {resp.text}")
    return resp.content


def search_invoices(business_id: str, **filters) -> dict[str, Any]:
    """
    GET /api/v1/invoice/{business_id}
    Search invoices with optional filters: irn, payment_status, invoice_type_code,
    issue_date, due_date, tax_currency_code, document_currency_code, size, page, sort_by.
    """
    settings = _get_settings()
    params = {
        "size": filters.get("size", 20),
        "page": filters.get("page", 1),
        "sort_by": filters.get("sort_by", "created_at"),
        "sort_direction_desc": filters.get("sort_direction_desc", True),
    }
    for key in ("irn", "payment_status", "invoice_type_code", "issue_date",
                "due_date", "tax_currency_code", "document_currency_code"):
        if filters.get(key):
            params[key] = filters[key]

    resp = requests.get(
        f"{_base_url(settings)}/api/v1/invoice/{business_id}",
        params=params,
        headers=_headers(settings),
        timeout=_TIMEOUT_SHORT,
    )
    if not resp.ok:
        raise EInvoiceError(f"FIRS search failed [{resp.status_code}]: {resp.text}")
    return resp.json() if resp.content else {}


def cancel_invoice(sales_invoice: str) -> dict[str, Any]:
    """
    Called on Sales Invoice cancellation.
    FIRS has no cancel endpoint — we mark the local record Cancelled only.
    If the invoice was never signed, we can simply cancel locally.
    """
    name = frappe.db.get_value("Nigeria E-Invoice", {"sales_invoice": sales_invoice}, "name")
    if not name:
        return {}

    frappe.db.set_value("Nigeria E-Invoice", name, "status", "Cancelled")
    frappe.db.set_value("Sales Invoice", sales_invoice, "ng_firs_status", "Cancelled")
    frappe.db.commit()
    return {"cancelled": True}


def check_irn_status(irn: str) -> dict[str, Any]:
    """Poll FIRS for the current status of an IRN (used by hourly poll)."""
    settings = _get_settings()
    resp = requests.get(
        f"{_base_url(settings)}/api/v1/invoice/confirm/{irn}",
        headers=_headers(settings),
        timeout=_TIMEOUT_SHORT,
    )
    if not resp.ok:
        raise EInvoiceError(f"FIRS IRN status check failed [{resp.status_code}]: {resp.text}")
    return resp.json() if resp.content else {}


# ── Entity lookup ─────────────────────────────────────────────────────────────

def get_entity(entity_id: str) -> dict[str, Any]:
    """GET /api/v1/entity/{id} — fetch registered business entity details."""
    settings = _get_settings()
    resp = requests.get(
        f"{_base_url(settings)}/api/v1/entity/{entity_id}",
        headers=_headers(settings),
        timeout=_TIMEOUT_SHORT,
    )
    if not resp.ok:
        raise EInvoiceError(f"FIRS entity lookup failed [{resp.status_code}]: {resp.text}")
    return resp.json() if resp.content else {}


def search_entities(reference: str = "", page: int = 1, size: int = 20) -> dict[str, Any]:
    """GET /api/v1/entity — search registered entities."""
    settings = _get_settings()
    resp = requests.get(
        f"{_base_url(settings)}/api/v1/entity",
        params={
            "size": size,
            "page": page,
            "sort_by": "created_at",
            "sort_direction_desc": True,
            "reference": reference,
        },
        headers=_headers(settings),
        timeout=_TIMEOUT_SHORT,
    )
    if not resp.ok:
        raise EInvoiceError(f"FIRS entity search failed [{resp.status_code}]: {resp.text}")
    return resp.json() if resp.content else {}


# ── Internal helpers ──────────────────────────────────────────────────────────

def _get_or_create_einvoice(sales_invoice: str):
    name = frappe.db.get_value("Nigeria E-Invoice", {"sales_invoice": sales_invoice}, "name")
    if name:
        return frappe.get_doc("Nigeria E-Invoice", name)

    from zinye_ng.nigeria.constants.invoice_types import get_invoice_type_code

    inv = frappe.get_doc("Sales Invoice", sales_invoice)
    type_code = get_invoice_type_code(
        "Sales Invoice",
        bool(inv.get("is_return")),
        bool(inv.get("is_debit_note")),
    )
    doc = frappe.new_doc("Nigeria E-Invoice")
    doc.sales_invoice = sales_invoice
    doc.status = "Pending"
    doc.invoice_type = type_code
    doc.invoice_number = sales_invoice
    doc.invoice_date = inv.posting_date
    doc.seller_tin = frappe.db.get_value("Company", inv.company, "ng_tin") or ""
    doc.buyer_tin = frappe.db.get_value("Customer", inv.customer, "ng_tin") or ""
    doc.total_excluding_vat = inv.net_total
    doc.grand_total = inv.grand_total
    doc.max_retries = _MAX_RETRIES
    doc.insert(ignore_permissions=True)
    frappe.db.commit()
    return doc


def _update_einvoice(doc, payload: dict, response: dict, status: str, error: str,
                     irn: str = "", csid: str = "", qr_data: str = ""):
    doc.status = status
    if irn:
        doc.irn = irn
    if csid:
        doc.csid = csid
    doc.payload = json.dumps(payload, indent=2, default=str)
    doc.response = json.dumps(response, indent=2, default=str)
    doc.error_message = error

    if status in ("Failed", "Auto-Retry"):
        doc.retry_count = (doc.retry_count or 0) + 1
        doc.last_retry_at = now_datetime()

    if status == "Submitted":
        doc.submitted_at = now_datetime()
        doc.vat_amount = (
            response.get("totalVAT")
            or response.get("total_vat")
            or response.get("tax_amount")
            or 0
        )
    if status == "Cleared":
        doc.cleared_at = now_datetime()

    if qr_data:
        _attach_qr_code(doc, qr_data)

    doc.save(ignore_permissions=True)
    frappe.db.commit()


def _attach_qr_code(einvoice_doc, qr_data: str):
    """Generate a QR code PNG from qr_data and attach it to the Nigeria E-Invoice."""
    try:
        import qrcode
        import io
        import base64

        img = qrcode.make(qr_data)
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        buf.seek(0)

        file_doc = frappe.get_doc({
            "doctype": "File",
            "file_name": f"qr_{einvoice_doc.name}.png",
            "content": base64.b64encode(buf.read()).decode(),
            "is_private": 0,
            "attached_to_doctype": "Nigeria E-Invoice",
            "attached_to_name": einvoice_doc.name,
            "attached_to_field": "qr_code",
        })
        file_doc.insert(ignore_permissions=True)
        einvoice_doc.qr_code = file_doc.file_url
    except ImportError:
        einvoice_doc.qr_code = qr_data
    except Exception as e:
        frappe.log_error(str(e), "FIRS QR Code Generation")
